apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: quarkus-build-pipeline
spec:
  params:
  - name: git-url
  - name: git-revision
    default: master
  - name: source-path
    default: .
  - name: image-registry
    default: docker.io
  - name: image-group
  - name: image-name
  - name: image-tag
    default: latest
  workspaces:
  - name: git-source
  tasks:
  - name: fetch-from-git
    taskRef:
      name: git-clone
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.git-revision)
    workspaces:
    - name: output
      workspace: git-source
  - name: build-code
    taskRef:
      name: quarkus-build
    params:
    - name: DIRECTORY
      value: $(params.source-path)
    - name: CACHE
      value: maven-repo-pvc
    - name: IMAGE_REGISTRY
      value: $(params.image-registry)
    - name: IMAGE_GROUP
      value: $(params.image-group)
    - name: IMAGE_NAME
      value: $(params.image-name)
    - name: IMAGE_TAG
      value: $(params.image-tag)
    runAfter:
    - fetch-from-git
    workspaces:
    - name: source
      workspace: git-source
