apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: quarkus-build
spec:
  params:
  - name: BUILDER_IMAGE
    description: The location of the s2i builder image.
    default: quay.io/quarkus/centos-quarkus-maven:20.1.0-java11
  - name: DIRECTORY
    description: The directory containing the app, relative to the source repository root
    default: .
  - name: INSECUREREGISTRY
    description: Whether to allow insecure registry
    default: "false"
  - name: IMAGE_REGISTRY
    description: The container registry to use
    default: docker.io
  - name: IMAGE_GROUP
    description: The group the container image will be part of
    default: tekton
  - name: IMAGE_NAME
    description: he name of the container image
  - name: IMAGE_TAG
    description: The tag of the container image.
    default: latest
  workspaces:
  - name: source
  - name: cache
  steps:
  - name: set-source-permissions
    command:
    - chmod
    - -R
    - a+w
    - .
    image: bash
    workingDir: $(workspaces.source.path)/$(params.DIRECTORY)
  - name: foo
    command:
    - ls
    - -als
    image: bash
    workingDir: $(workspaces.source.path)/$(params.DIRECTORY)
  - name: quarkus-add-jib-extension
    command:
    - mvn
    - -X
    - quarkus:add-extension
    - -Dmaven.repo.local=$(workspaces.cache.path)/.m2
    - -Dextensions="container-image-jib"
    image: $(params.BUILDER_IMAGE)
    securityContext:
      privileged: true
    workingDir: $(workspaces.source.path)/$(params.DIRECTORY)
    env:
    - name: HOME
      value: /workspace
  - name: maven-build
    command:
    - mvn
    - -Dmaven.repo.local=$(workspaces.cache.path)/.m2
    - -Dquarkus.container-image.build=true
    - -Dquarkus.container-image.builder=jib
    - -Dquarkus.container-image.push=true
    - -Dquarkus.container-image.insecure=$(params.INSECUREREGISTRY)
    - -Dquarkus.container-image.registry=$(params.IMAGE_REGISTRY)
    - -Dquarkus.container-group.registry=$(params.IMAGE_GROUP)
    - -Dquarkus.container-name.registry=$(params.IMAGE_NAME)
    - -Dquarkus.container-tag.registry=$(params.IMAGE_TAG)
    - -X
    - package
    image: $(params.BUILDER_IMAGE)
    securityContext:
      privileged: true
    workingDir: $(workspaces.source.path)/$(params.DIRECTORY)
    env:
    - name: HOME
      value: /workspace
